# docker-compose.yml
version: "3"

services:
  server:
    image: node:16-alpine
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3001:8080
    environment:
      - PORT=3001
    command: sh -c "npm install && npm run start"